package com.ravemaster.recipeapp.api.getfeed.models;

import java.util.ArrayList;

public class Recipe {
    public String nutrition_visibility;
    public String country;
    public ArrayList<Instruction> instructions;
    public String keywords;
    public ArrayList<Object> facebook_posts;
    public String language;
    public String seo_path;
    public UserRatings user_ratings;
    public Price price;
    public int id;
    public Object brand;
    public String slug;
    public String servings_noun_singular;
    public int show_id;
    public int prep_time_minutes;
    public boolean is_subscriber_content;
    public ArrayList<Section> sections;
    public Object brand_id;
    public ArrayList<Tag> tags;
    public Nutrition nutrition;
    public boolean is_app_only;
    public String name;
    public ArrayList<Compilation> compilations;
    public int num_servings;
    public int _id;
    public int buzz_id;
    public boolean tips_and_ratings_enabled;
    public String aspect_ratio;
    public String _index;
    public Section section;
    public int created_at;
    public String description;
    public String draft_status;
    public String inspired_by_url;
    public String thumbnail_url;
    public String thumbnail_alt_text;
    public int total_time_minutes;
    public String video_url;
    public int updated_at;
    public ArrayList<Credit> credits;
    public int approved_at;
    public boolean is_one_top;
    public String servings_noun_plural;
    public ArrayList<Rendition> renditions;
    public String beauty_url;
    public boolean is_shoppable;
    public ArrayList<Topic> topics;
    public TotalTimeTier total_time_tier;
    public String _type;
    public String _op_type;
    public String video_ad_content;
    public String seo_title;
    public String yields;
    public String original_video_url;
    public String canonical_id;
    public int cook_time_minutes;
    public String promotion;
    public int video_id;
}
